resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: pipeline-resource
  type: git
  source:
    uri: {{pipeline-resource-uri}}
    branch: {{pipeline-resource-branch}}

- name: cf-env
  type: cf-cli-resource
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    org: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

- name: pcf-resource
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: block1
  plan:
  - task: configure
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: bash
        args:
        - -excl
        - |-
          cat > cf_command/params.yml <<EOF
          command: delete
          app_name: {{app-to-be-deleted}}
          delete_mapped_routes: true
          EOF
      outputs:
        - name: cf_command
  - put: cf-delete
    resource: cf-env
    params:
      command: delete
      command_file: cf_command/params.yml

