resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:

- name: cf-env
  type: cf-cli-resource
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    org: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true


jobs:
- name: start{{the-app}}
  plan:
  - task: configure
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: bash
        args:
        - -excl
        - |-
          cat > cf_command/params.yml <<EOF
          command: start
          app_name: {{the-app}}
          EOF
      outputs:
        - name: cf_command
  - put: start-the-app
    resource: cf-env
    params:
      command: start
      command_file: cf_command/params.yml

