---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
inputs:
  - name: code
  - name: pipeline
outputs:
  - name: cf_command
run:
  path: pipeline/tasks/cf-cli.sh
